### ISSUE TITLE
preprocessing.py doesnt work 

### ISSUE THREAD

**Issue by log-xp** [sankalp1999/code_qa#1]
I am getting a error at parser = get_parser(language)

the library has not changed also , did it work for you , u have any idea of workaround ?

**Comment by sankalp1999** [comment]
Thanks!
This is a recent issue. We need to downgrade tree-sitter

https://github.com/modelscope/agentscope/issues/245

**Comment by sankalp1999** [comment]
`pip install tree-sitter==0.21.3`

**Comment by log-xp** [comment]
yeah now it works thanks 😄
